# Generated by Django 2.1.5 on 2019-01-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CauHoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('noi_dung', models.TextField()),
                ('co_cau_hoi_nho', models.BooleanField(default=False)),
                ('ky_hoc', models.CharField(choices=[('GKI', 'giữa kỳ I'), ('CKI', 'cuối kỳ I'), ('GKII', 'giữa kỳ II'), ('CKII', 'cuối kỳ II')], max_length=4)),
                ('dang', models.CharField(choices=[('TN', 'trắc nhiệm'), ('DT', 'điền từ'), ('TL', 'tự luận')], max_length=2)),
                ('the_loai', models.CharField(choices=[('txt', 'văn bản'), ('img', 'hình ảnh'), ('au', 'âm thanh'), ('vi', 'phim')], max_length=3)),
                ('dinh_kem', models.FileField(blank=True, upload_to='uploads/')),
                ('do_kho', models.CharField(choices=[('D', 'dễ'), ('TB', 'trung bình'), ('K', 'khó')], max_length=2)),
                ('cau_hoi_nho', models.ManyToManyField(db_table='cau_hoi_da', related_name='_cauhoi_cau_hoi_nho_+', to='giao_vien.CauHoi')),
            ],
            options={
                'db_table': 'cau_hoi',
            },
        ),
        migrations.CreateModel(
            name='ChuDe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'chu_de',
            },
        ),
        migrations.CreateModel(
            name='ChuDeMon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chu_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chu_de_mon', to='giao_vien.ChuDe')),
            ],
            options={
                'db_table': 'chu_de_mon',
            },
        ),
        migrations.CreateModel(
            name='DapAn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('dung', models.BooleanField(default=False)),
                ('chu_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hoi', to='giao_vien.ChuDe')),
            ],
            options={
                'db_table': 'dap_an',
            },
        ),
        migrations.CreateModel(
            name='DapAnCauHoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cau_hoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dap_an_cau_hoi', to='giao_vien.CauHoi')),
                ('dap_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dap_an_cau_hoi', to='giao_vien.DapAn')),
            ],
            options={
                'db_table': 'dap_an_cau_hoi',
            },
        ),
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=20)),
                ('ho', models.CharField(max_length=20)),
                ('ten_dem', models.CharField(blank=True, max_length=20)),
                ('hieu_pho', models.BooleanField(default=False)),
                ('gioi_tinh', models.CharField(choices=[('nam', 'nam'), ('nữ', 'nữ')], max_length=3)),
            ],
            options={
                'db_table': 'giao_vien',
            },
        ),
        migrations.CreateModel(
            name='GiaoVienMon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giao_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giao_vien_mon', to='giao_vien.GiaoVien')),
            ],
            options={
                'db_table': 'giao_vien_mon',
            },
        ),
        migrations.CreateModel(
            name='Mon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('khoi', models.IntegerField()),
                ('chu_de', models.ManyToManyField(related_name='mon', through='giao_vien.ChuDeMon', to='giao_vien.ChuDe')),
            ],
            options={
                'db_table': 'mon',
            },
        ),
        migrations.CreateModel(
            name='Truong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'truong',
            },
        ),
        migrations.AddField(
            model_name='giaovienmon',
            name='mon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giao_vien_mon', to='giao_vien.Mon'),
        ),
        migrations.AddField(
            model_name='giaovien',
            name='mon',
            field=models.ManyToManyField(related_name='giao_vien', through='giao_vien.GiaoVienMon', to='giao_vien.Mon'),
        ),
        migrations.AddField(
            model_name='giaovien',
            name='truong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giao_vien', to='giao_vien.Truong'),
        ),
        migrations.AddField(
            model_name='dapan',
            name='mon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hoi', to='giao_vien.Mon'),
        ),
        migrations.AddField(
            model_name='chudemon',
            name='mon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chu_de_mon', to='giao_vien.Mon'),
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='chu_de',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hoi_chu_de', to='giao_vien.ChuDe'),
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='dap_an',
            field=models.ManyToManyField(related_name='cau_hoi_dap_an', through='giao_vien.DapAnCauHoi', to='giao_vien.DapAn'),
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='giao_vien_tao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hoi_giao_vien', to='giao_vien.GiaoVien'),
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='mon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hoi_mon', to='giao_vien.Mon'),
        ),
    ]
