# Generated by Django 2.1.5 on 2019-01-30 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('ten', models.CharField(max_length=20)),
                ('ho', models.CharField(max_length=20)),
                ('ten_dem', models.CharField(blank=True, max_length=20)),
                ('hieu_pho', models.BooleanField(default=False)),
                ('gioi_tinh', models.CharField(choices=[('nam', 'nam'), ('nữ', 'nữ')], max_length=3)),
            ],
            options={
                'db_table': 'giao_vien',
            },
        ),
        migrations.CreateModel(
            name='CauHoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('noi_dung', models.TextField()),
                ('diem', models.IntegerField(null=True)),
                ('co_cau_hoi_nho', models.BooleanField(default=False)),
                ('ky_hoc', models.CharField(choices=[('GKI', 'giữa kỳ I'), ('CKI', 'cuối kỳ I'), ('GKII', 'giữa kỳ II'), ('CKII', 'cuối kỳ II')], max_length=4)),
                ('dang', models.CharField(choices=[('TN', 'trắc nhiệm'), ('DT', 'điền từ'), ('TL', 'tự luận')], max_length=2)),
                ('the_loai', models.CharField(choices=[('txt', 'văn bản'), ('img', 'hình ảnh'), ('au', 'âm thanh'), ('vi', 'phim')], max_length=3)),
                ('dinh_kem', models.FileField(blank=True, upload_to='uploads/')),
                ('do_kho', models.CharField(choices=[('D', 'dễ'), ('TB', 'trung bình'), ('K', 'khó')], max_length=2)),
                ('cau_hoi_nho', models.ManyToManyField(db_table='cau_hoi_da', related_name='_cauhoi_cau_hoi_nho_+', to='giao_vien.CauHoi')),
            ],
            options={
                'db_table': 'cau_hoi',
            },
        ),
        migrations.CreateModel(
            name='ChuDe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'chu_de',
            },
        ),
        migrations.CreateModel(
            name='DapAn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('dung', models.BooleanField(default=False)),
                ('chu_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hoi', to='giao_vien.ChuDe')),
            ],
            options={
                'db_table': 'dap_an',
            },
        ),
        migrations.CreateModel(
            name='De',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('ky_hoc', models.CharField(choices=[('GKI', 'giữa kỳ I'), ('CKI', 'cuối kỳ I'), ('GKII', 'giữa kỳ II'), ('CKII', 'cuối kỳ II')], max_length=4)),
                ('dien_tu', models.ManyToManyField(db_table='de_dien_tu', related_name='de_dien_tu', to='giao_vien.CauHoi')),
            ],
            options={
                'db_table': 'de',
            },
        ),
        migrations.CreateModel(
            name='Mon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('khoi', models.IntegerField()),
                ('chu_de', models.ManyToManyField(db_table='chu_de_mon', related_name='mon', to='giao_vien.ChuDe')),
            ],
            options={
                'db_table': 'mon',
            },
        ),
        migrations.CreateModel(
            name='Truong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'truong',
            },
        ),
        migrations.AddField(
            model_name='de',
            name='mon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='de', to='giao_vien.Mon'),
        ),
        migrations.AddField(
            model_name='de',
            name='trac_nhiem',
            field=models.ManyToManyField(db_table='de_trac_nhiem', related_name='de_trac_nhiem', to='giao_vien.CauHoi'),
        ),
        migrations.AddField(
            model_name='de',
            name='tu_luan',
            field=models.ManyToManyField(db_table='de_tu_luan', related_name='de_tu_luan', to='giao_vien.CauHoi'),
        ),
        migrations.AddField(
            model_name='dapan',
            name='mon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hoi', to='giao_vien.Mon'),
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='chu_de',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hoi_chu_de', to='giao_vien.ChuDe'),
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='dap_an',
            field=models.ManyToManyField(db_table='dap_an_cau_hoi', related_name='cau_hoi_dap_an', to='giao_vien.DapAn'),
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='giao_vien_tao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hoi_giao_vien', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='mon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hoi_mon', to='giao_vien.Mon'),
        ),
        migrations.AddField(
            model_name='giaovien',
            name='mon',
            field=models.ManyToManyField(db_table='giao_vien_mon', related_name='giao_vien', to='giao_vien.Mon'),
        ),
        migrations.AddField(
            model_name='giaovien',
            name='truong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giao_vien', to='giao_vien.Truong'),
        ),
    ]
