# Generated by Django 2.1.5 on 2019-02-12 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giao_vien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietDe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cau_hoi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chi_tiet_de_cau_hoi', to='giao_vien.CauHoi')),
            ],
            options={
                'db_table': 'chi_tiet_de',
            },
        ),
        migrations.RemoveField(
            model_name='de',
            name='dien_tu',
        ),
        migrations.RemoveField(
            model_name='de',
            name='trac_nhiem',
        ),
        migrations.RemoveField(
            model_name='de',
            name='tu_luan',
        ),
        migrations.AddField(
            model_name='de',
            name='cau_hoi_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='de',
            name='dap_an_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dapan',
            name='chu_de',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dap_an_chu_de', to='giao_vien.ChuDe'),
        ),
        migrations.AlterField(
            model_name='dapan',
            name='mon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dap_an_mon', to='giao_vien.Mon'),
        ),
        migrations.AlterField(
            model_name='de',
            name='mon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='de_mon', to='giao_vien.Mon'),
        ),
        migrations.AlterField(
            model_name='giaovien',
            name='mon',
            field=models.ManyToManyField(db_table='giao_vien_mon', related_name='giao_vien_mon', to='giao_vien.Mon'),
        ),
        migrations.AlterField(
            model_name='giaovien',
            name='truong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giao_vien_truong', to='giao_vien.Truong'),
        ),
        migrations.AlterField(
            model_name='mon',
            name='chu_de',
            field=models.ManyToManyField(db_table='chu_de_mon', related_name='mon_chu_de', to='giao_vien.ChuDe'),
        ),
        migrations.AddField(
            model_name='chitietde',
            name='de',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_de_de', to='giao_vien.De'),
        ),
        migrations.AddField(
            model_name='de',
            name='cau_hoi',
            field=models.ManyToManyField(related_name='de_cau_hoi', through='giao_vien.ChiTietDe', to='giao_vien.CauHoi'),
        ),
    ]
