# Generated by Django 2.1.5 on 2019-02-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giao_vien', '0002_auto_20190212_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giaovien',
            name='ho',
        ),
        migrations.RemoveField(
            model_name='giaovien',
            name='ten',
        ),
        migrations.RemoveField(
            model_name='giaovien',
            name='ten_dem',
        ),
        migrations.AddField(
            model_name='giaovien',
            name='ho_ten',
            field=models.CharField(default='Nguyễn A', max_length=100),
            preserve_default=False,
        ),
    ]
