# Generated by Django 2.1.5 on 2019-02-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giao_vien', '0003_auto_20190214_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhoi',
            name='dang',
            field=models.CharField(choices=[('TN', 'Trắc nhiệm'), ('DT', 'Điền từ'), ('TL', 'Tự luận')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='do_kho',
            field=models.CharField(choices=[('D', 'Dễ'), ('TB', 'Trung bình'), ('K', 'Khó')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='ky_hoc',
            field=models.CharField(choices=[('GKI', 'Giữa kỳ I'), ('CKI', 'Cuối kỳ I'), ('GKII', 'Giữa kỳ II'), ('CKII', 'Cuối kỳ II')], max_length=4),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='the_loai',
            field=models.CharField(choices=[('txt', 'Văn bản'), ('img', 'Hình ảnh'), ('au', 'Âm thanh'), ('vi', 'Phim')], max_length=3),
        ),
    ]
