# Generated by Django 2.1.5 on 2019-02-15 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giao_vien', '0004_auto_20190214_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='dapan',
            name='cau_hoi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dap_an_cau_hoi', to='giao_vien.CauHoi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='dang',
            field=models.CharField(choices=[('Trắc nhiệm', 'Trắc nhiệm'), ('Điền từ', 'Điền từ'), ('Tự luận', 'Tự luận')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='do_kho',
            field=models.CharField(choices=[('Dễ', 'Dễ'), ('Trung bình', 'Trung bình'), ('Khó', 'Khó')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='ky_hoc',
            field=models.CharField(choices=[('Giữa kỳ I', 'Giữa kỳ I'), ('Cuối kỳ I', 'Cuối kỳ I'), ('Giữa kỳ II', 'Giữa kỳ II'), ('Cuối kỳ II', 'Cuối kỳ II')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='the_loai',
            field=models.CharField(choices=[('Văn bản', 'Văn bản'), ('Hình ảnh', 'Hình ảnh'), ('Âm thanh', 'Âm thanh'), ('Phim', 'Phim')], max_length=20),
        ),
        migrations.AlterField(
            model_name='de',
            name='ky_hoc',
            field=models.CharField(choices=[('Giữa kỳ I', 'Giữa kỳ I'), ('Cuối kỳ I', 'Cuối kỳ I'), ('Giữa kỳ II', 'Giữa kỳ II'), ('Cuối kỳ II', 'Cuối kỳ II')], max_length=20),
        ),
    ]
