# Generated by Django 2.1.5 on 2019-02-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giao_vien', '0005_auto_20190215_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauhoi',
            name='la_cau_hoi_nho',
            field=models.BooleanField(default=False),
        ),
    ]
