# Generated by Django 2.1.5 on 2019-02-15 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giao_vien', '0006_cauhoi_la_cau_hoi_nho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhoi',
            name='mon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hoi_mon', related_query_name='cau_hoi_mon', to='giao_vien.Mon'),
        ),
    ]
