# Generated by Django 2.1.5 on 2019-02-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giao_vien', '0007_auto_20190215_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhoi',
            name='diem',
            field=models.FloatField(null=True),
        ),
    ]
