# Generated by Django 2.1.5 on 2019-02-18 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giao_vien', '0008_auto_20190218_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cauhoi',
            old_name='diem',
            new_name='so_diem',
        ),
    ]
