# Generated by Django 2.1.5 on 2019-02-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giao_vien', '0009_auto_20190218_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitietde',
            name='cau_hoi',
        ),
        migrations.RemoveField(
            model_name='chitietde',
            name='de',
        ),
        migrations.RemoveField(
            model_name='de',
            name='cau_hoi',
        ),
        migrations.DeleteModel(
            name='ChiTietDe',
        ),
    ]
