# Generated by Django 2.1.5 on 2019-02-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giao_vien', '0010_auto_20190218_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='de',
            name='ten',
        ),
    ]
