# Generated by Django 2.1.5 on 2019-02-18 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giao_vien', '0011_remove_de_ten'),
    ]

    operations = [
        migrations.AddField(
            model_name='de',
            name='giao_vien_tao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='de_giao_vien', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='de',
            name='thoi_gian',
            field=models.CharField(default='90 phút', max_length=20),
            preserve_default=False,
        ),
    ]
